# Generated by Django 2.1.15 on 2020-05-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSHconnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=130)),
                ('port', models.CharField(max_length=6)),
                ('ip', models.GenericIPAddressField()),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
