# Generated by Django 2.2 on 2020-05-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bashscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=3)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.BashScript')),
            ],
        ),
    ]
