# Generated by Django 2.2 on 2020-05-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scriptlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptlevel',
            name='point',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
