# Generated by Django 2.2 on 2020-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200523_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptlevel',
            name='name',
            field=models.CharField(max_length=130),
        ),
    ]
