# Generated by Django 2.2 on 2020-05-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200523_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=130)),
                ('point', models.CharField(max_length=1)),
            ],
        ),
    ]
