# Generated by Django 2.2 on 2020-05-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_words_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words_Point',
            new_name='WordsPoint',
        ),
    ]
