# Generated by Django 2.2 on 2020-05-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200523_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='bashscript',
            name='point',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
